# Generated by Django 4.1.6 on 2023-05-09 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='productlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=200)),
                ('qty', models.CharField(max_length=100)),
                ('rate', models.CharField(max_length=10)),
            ],
        ),
    ]
