# Generated by Django 4.1.6 on 2023-05-09 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billapp', '0002_hardwareproduct_plumbingproduct_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='billcal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.CharField(max_length=10)),
                ('discount', models.CharField(max_length=10)),
                ('todiscount', models.CharField(max_length=10)),
                ('amount', models.CharField(max_length=10)),
            ],
        ),
    ]
