# Generated by Django 4.1.6 on 2023-05-09 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billapp', '0003_billcal'),
    ]

    operations = [
        migrations.CreateModel(
            name='partcal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('btotal', models.CharField(max_length=11)),
                ('bdiscount', models.CharField(max_length=11)),
                ('btodiscount', models.CharField(max_length=11)),
                ('bamount', models.CharField(max_length=11)),
            ],
        ),
    ]
