# Generated by Django 4.1.6 on 2023-05-09 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billapp', '0004_partcal'),
    ]

    operations = [
        migrations.CreateModel(
            name='part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=100)),
                ('qty', models.CharField(max_length=10)),
                ('rate', models.CharField(max_length=10)),
                ('peccen', models.CharField(max_length=100)),
                ('come', models.CharField(max_length=100)),
                ('totalfee', models.CharField(max_length=10)),
            ],
        ),
    ]
