# Generated by Django 4.1.6 on 2023-05-09 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billapp', '0005_part'),
    ]

    operations = [
        migrations.CreateModel(
            name='partper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datt', models.CharField(max_length=30)),
                ('timm', models.CharField(max_length=30)),
                ('bproduct', models.CharField(max_length=500)),
                ('bqty', models.CharField(max_length=300)),
                ('brate', models.CharField(max_length=300)),
                ('bper', models.CharField(max_length=30)),
                ('bcfee', models.CharField(max_length=300)),
                ('btfee', models.CharField(max_length=300)),
                ('btotal', models.CharField(max_length=300)),
                ('bdis', models.CharField(max_length=30)),
                ('btodisp', models.CharField(max_length=30)),
                ('bkad', models.CharField(max_length=30)),
                ('bnumm', models.CharField(max_length=30)),
            ],
        ),
    ]
