# Generated by Django 4.1.6 on 2023-05-09 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billapp', '0006_partper'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partper',
            name='bproduct',
            field=models.CharField(max_length=1000),
        ),
    ]
