# Generated by Django 4.1.6 on 2023-05-09 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billapp', '0007_alter_partper_bproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='billone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oneprod', models.CharField(max_length=100)),
                ('oneqty', models.CharField(max_length=50)),
                ('onerate', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='billper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dddat', models.CharField(max_length=20)),
                ('tttim', models.CharField(max_length=20)),
                ('proddd', models.CharField(max_length=1000)),
                ('qqty', models.CharField(max_length=400)),
                ('rrate', models.CharField(max_length=400)),
                ('teto', models.CharField(max_length=300)),
                ('dedis', models.CharField(max_length=300)),
                ('tetodis', models.CharField(max_length=300)),
                ('dakad', models.CharField(max_length=300)),
                ('ssnumm', models.CharField(max_length=300)),
            ],
        ),
    ]
