# Generated by Django 4.1.6 on 2023-05-09 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billapp', '0008_billone_billper'),
    ]

    operations = [
        migrations.AddField(
            model_name='billone',
            name='onenoq',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]
