# Generated by Django 4.1.6 on 2023-05-09 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billapp', '0011_alter_partcal_bamount_alter_partcal_bdiscount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billcal',
            name='amount',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='billcal',
            name='discount',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='billcal',
            name='todiscount',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='billcal',
            name='total',
            field=models.CharField(max_length=50),
        ),
    ]
