# Generated by Django 4.1.6 on 2023-05-09 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billapp', '0012_alter_billcal_amount_alter_billcal_discount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='billone',
            name='onepra',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]
