# Generated by Django 4.1.6 on 2023-05-09 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billapp', '0013_billone_onepra'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='noqty',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='part',
            name='toqrate',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
