# Generated by Django 4.2.1 on 2023-05-10 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billapp', '0015_billper_perp'),
    ]

    operations = [
        migrations.AddField(
            model_name='partper',
            name='borr',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
