# Generated by Django 4.2.1 on 2023-05-10 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billapp', '0016_partper_borr'),
    ]

    operations = [
        migrations.AddField(
            model_name='partper',
            name='bnofq',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
