# Generated by Django 4.2.1 on 2023-05-10 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billapp', '0018_alter_billper_dddat_alter_billper_tttim'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billper',
            name='nofqty',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='billper',
            name='perp',
            field=models.CharField(max_length=700),
        ),
        migrations.AlterField(
            model_name='billper',
            name='qqty',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='billper',
            name='rrate',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='billper',
            name='teto',
            field=models.CharField(max_length=1000),
        ),
    ]
