# Generated by Django 4.2.1 on 2023-05-10 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billapp', '0019_alter_billper_nofqty_alter_billper_perp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billper',
            name='dakad',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='billper',
            name='dedis',
            field=models.CharField(max_length=700),
        ),
        migrations.AlterField(
            model_name='billper',
            name='ssnumm',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='billper',
            name='tetodis',
            field=models.CharField(max_length=700),
        ),
    ]
