# Generated by Django 4.2.1 on 2023-05-10 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billapp', '0021_alter_billper_qqty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partper',
            name='bcfee',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='partper',
            name='bnofq',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='partper',
            name='borr',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='partper',
            name='bper',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='partper',
            name='bproduct',
            field=models.CharField(max_length=1500),
        ),
        migrations.AlterField(
            model_name='partper',
            name='bqty',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='partper',
            name='brate',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='partper',
            name='btfee',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='partper',
            name='btotal',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='partper',
            name='datt',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='partper',
            name='timm',
            field=models.CharField(max_length=1000),
        ),
    ]
