# Generated by Django 4.2.1 on 2023-05-10 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billapp', '0022_alter_partper_bcfee_alter_partper_bnofq_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partper',
            name='bdis',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='partper',
            name='bkad',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='partper',
            name='bnumm',
            field=models.CharField(max_length=1500),
        ),
        migrations.AlterField(
            model_name='partper',
            name='btodisp',
            field=models.CharField(max_length=1000),
        ),
    ]
