# Generated by Django 4.2.1 on 2023-05-12 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billapp', '0024_billing'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='rate',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
