# Generated by Django 4.2.1 on 2023-05-12 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billapp', '0025_billing_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
