# Generated by Django 4.2.1 on 2023-05-12 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billapp', '0029_mymodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mymodel',
            name='field1',
        ),
        migrations.RemoveField(
            model_name='mymodel',
            name='field2',
        ),
        migrations.RemoveField(
            model_name='mymodel',
            name='field3',
        ),
        migrations.RemoveField(
            model_name='mymodel',
            name='field4',
        ),
        migrations.AddField(
            model_name='mymodel',
            name='name1',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mymodel',
            name='name10',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mymodel',
            name='name2',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mymodel',
            name='name3',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mymodel',
            name='name4',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mymodel',
            name='name5',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mymodel',
            name='name6',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mymodel',
            name='name7',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mymodel',
            name='name8',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mymodel',
            name='name9',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
