# Generated by Django 4.2.1 on 2023-05-12 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billapp', '0030_remove_mymodel_field1_remove_mymodel_field2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='mytiger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name1', models.CharField(max_length=100)),
                ('name2', models.CharField(max_length=100)),
                ('name3', models.CharField(max_length=100)),
                ('name4', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='mymodel',
            name='name1',
        ),
        migrations.RemoveField(
            model_name='mymodel',
            name='name10',
        ),
        migrations.RemoveField(
            model_name='mymodel',
            name='name2',
        ),
        migrations.RemoveField(
            model_name='mymodel',
            name='name3',
        ),
        migrations.RemoveField(
            model_name='mymodel',
            name='name4',
        ),
        migrations.RemoveField(
            model_name='mymodel',
            name='name5',
        ),
        migrations.RemoveField(
            model_name='mymodel',
            name='name6',
        ),
        migrations.RemoveField(
            model_name='mymodel',
            name='name7',
        ),
        migrations.RemoveField(
            model_name='mymodel',
            name='name8',
        ),
        migrations.RemoveField(
            model_name='mymodel',
            name='name9',
        ),
        migrations.AddField(
            model_name='mymodel',
            name='field1',
            field=models.CharField(default=11, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mymodel',
            name='field2',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mymodel',
            name='field3',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mymodel',
            name='field4',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
