# Generated by Django 4.2.1 on 2023-05-12 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billapp', '0031_mytiger_remove_mymodel_name1_remove_mymodel_name10_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mytiger',
            name='name10',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mytiger',
            name='name5',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mytiger',
            name='name6',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mytiger',
            name='name7',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mytiger',
            name='name8',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mytiger',
            name='name9',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
