# Generated by Django 4.2.1 on 2023-05-12 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billapp', '0032_mytiger_name10_mytiger_name5_mytiger_name6_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mymodel',
            name='field1',
        ),
    ]
