# Generated by Django 4.2.1 on 2023-05-12 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billapp', '0034_mytiger_name11'),
    ]

    operations = [
        migrations.DeleteModel(
            name='partper',
        ),
    ]
