# Generated by Django 4.2.1 on 2023-05-13 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billapp', '0035_delete_partper'),
    ]

    operations = [
        migrations.CreateModel(
            name='partper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datt', models.CharField(max_length=100)),
                ('timm', models.CharField(max_length=100)),
                ('bproduct', models.CharField(max_length=150)),
            ],
        ),
    ]
