# Generated by Django 4.2.1 on 2023-05-13 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billapp', '0036_partper'),
    ]

    operations = [
        migrations.AddField(
            model_name='partper',
            name='bnofq',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='partper',
            name='borr',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='partper',
            name='bqty',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='partper',
            name='brate',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
