# Generated by Django 4.2.1 on 2023-05-13 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billapp', '0038_partper_bcfee_partper_bper_partper_btfee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partper',
            name='bdis',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='partper',
            name='bkad',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='partper',
            name='bnumm',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='partper',
            name='btodisp',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
