# Generated by Django 4.2.1 on 2023-05-13 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billapp', '0039_partper_bdis_partper_bkad_partper_bnumm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mytiger',
            name='name12',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
