# Generated by Django 4.2.1 on 2023-05-14 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billapp', '0041_mytiger_name13'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partper',
            name='bproduct',
            field=models.CharField(max_length=1050),
        ),
        migrations.AlterField(
            model_name='partper',
            name='datt',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='partper',
            name='timm',
            field=models.CharField(max_length=1000),
        ),
    ]
