# Generated by Django 4.2.1 on 2023-05-14 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billapp', '0044_alter_partper_bdis_alter_partper_bkad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mytiger',
            name='name1',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='mytiger',
            name='name2',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='mytiger',
            name='name3',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='mytiger',
            name='name4',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='mytiger',
            name='name5',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='mytiger',
            name='name6',
            field=models.CharField(max_length=1000),
        ),
    ]
