# Generated by Django 4.2.1 on 2023-05-14 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billapp', '0046_alter_mytiger_name7_alter_mytiger_name8_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mytiger',
            name='name11',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='mytiger',
            name='name12',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='mytiger',
            name='name13',
            field=models.CharField(max_length=1000),
        ),
    ]
