# Generated by Django 4.2.1 on 2023-05-14 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billapp', '0048_alter_part_noqty_alter_part_qty_alter_part_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billone',
            name='onenoq',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='billone',
            name='onepra',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='billone',
            name='oneqty',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='billone',
            name='onerate',
            field=models.CharField(max_length=100),
        ),
    ]
