# Generated by Django 4.2.1 on 2023-05-14 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billapp', '0049_alter_billone_onenoq_alter_billone_onepra_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electricproduct',
            name='rate',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='hardwareproduct',
            name='rate',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='plumbingproduct',
            name='rate',
            field=models.CharField(max_length=20),
        ),
    ]
